[tool.poetry]
name = "seed"
version = "0.1.0"
description = ""
authors = ["mammadov115 <mehman.mammadov182@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
faker = "^40.38.0"
psycopg2-binary = "^2.9.12"
tqdm = "^4.70.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
